name: build-dev2

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    env:
      BUILD_TYPE: Release
    steps:

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3
      
    - name: Build llvm
      run: |
        git clone --branch dev --depth 1 https://github.com/NewWorldComingSoon/llvm-msvc
        cmake -Bbuild -DHAVE_STD_IS_TRIVIALLY_COPYABLE=0 -DLLVM_TOOL_LLVM_SHLIB_BUILD=off -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_ZLIB=OFF -DCMAKE_BUILD_TYPE=release -DLLVM_USE_CRT_RELEASE=MT -DCPACK_GENERATOR=ZIP "-DCMAKE_INSTALL_PREFIX=$pwd\\prefix" -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_PROJECTS="clang;lld" llvm-msvc\\llvm
        cmake --build build --config Release
    - name: Package llvm
      run: |
        cmake --build build --target package --config Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: llvm-msvc
        path: build/*.zip
