name: build-dev

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    env:
      BUILD_TYPE: Release
    steps:
   
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3
    
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.7.0
      
    - name: Build llvm
      run: |
        git clone --branch dev --depth 1 https://github.com/NewWorldComingSoon/llvm-msvc
        cmake -G"Visual Studio 16 2019" -Bbuild -DHAVE_STD_IS_TRIVIALLY_COPYABLE=0 -DLLVM_TOOL_LLVM_SHLIB_BUILD=off -DLLVM_ENABLE_LIBXML2=ON -DLLVM_USE_CRT_RELEASE=MT -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=ZIP "-DCMAKE_INSTALL_PREFIX=$pwd\\prefix" -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_PROJECTS="clang;lld" llvm-msvc\\llvm
        cmake --build build --config Release

    - name: Package llvm
      run: |
        cmake --build build --target package --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: llvm-msvc
        path: build/*.zip
