name: build-dev

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch

jobs:
  build:
    name: Build llvm-msvc 
    runs-on: windows-latest
    steps:
    - name: Install dependency
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install cmake

    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
      with:
        sdk-version: 19041

    - name: Build llvm
      run: |
        git clone --branch dev --depth 1 https://github.com/NewWorldComingSoon/llvm-msvc
        cmake -G "Visual Studio 17 2022" -Bbuild -DHAVE_STD_IS_TRIVIALLY_COPYABLE=0 -DLLVM_TOOL_LLVM_SHLIB_BUILD=off -DLLVM_ENABLE_LIBXML2=ON -DLLVM_USE_CRT_RELEASE=MT -DCMAKE_CONFIGURATION_TYPES="Release" -DCPACK_GENERATOR=ZIP "-DCMAKE_INSTALL_PREFIX=$pwd\\prefix" -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_PROJECTS="clang;lld" llvm-msvc\\llvm
        cmake --build build

    - name: Package llvm
      run: |
        cmake --build build --target package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: llvm-msvc
        path: build/*.zip
